# Description: WP1: Longevity
---
version: 1
id: wp1_longevity
phases:
- id: init
  sessions:
  - tasks:
    - template_id: init
- id: build
  sessions:
  - tasks:
    - template_id: build_create
- id: single_user_1
  sessions:
  - tasks:
    - template_id: single_user
